import { Properties } from "./type";

const properties: Properties[] = [
  {
    id: 1,
    title: "Modern Bungalow",
    category: "Bungalow",
    price: "₦2,000,000",
    img: "/flat1.jpg",
  },
  {
    id: 2,
    title: "Modern Bungalow",
    category: "Bungalow",
    price: "₦2,500,000",
    img: "/flat2.jpg",
  },
  {
    id: 3,
    title: "Duplex",
    category: "Duplex",
    price: "₦1,000,000",
    img: "/flat3.jpg",
  },
  {
    id: 4,
    title: "Two bedroom apartment",
    category: "Apartment",
    price: "₦1,200,000",
    img: "/flat4.jpg",
  },
  {
    id: 5,
    title: "Modern Bungalow",
    category: "Bungalow",
    price: "₦1,500,000",
    img: "/flat5.jpg",
  },
  {
    id: 6,
    title: "Modern Bungalow",
    category: "Bungalow",
    price: "₦1,200,000",
    img: "/flat6.jpg",
  },
  {
    id: 7,
    title: "Modern Bungalow",
    category: "Bungalow",
    price: "₦1,100,000",
    img: "/flat7.jpg",
  },
  {
    id: 8,
    title: "Duplex",
    category: "Duplex",
    price: "₦1,800,000",
    img: "/flat8.jpg",
  },
  {
    id: 9,
    title: "Two Bedroom Apartment",
    category: "Apartment",
    price: "₦2,200,000",
    img: "/flat9.jpg",
  },
  {
    id: 10,
    title: "Modern Bungalow",
    category: "Bungalow",
    price: "₦1,200,000",
    img: "/flat2.jpg",
  },
  {
    id: 11,
    title: "Duplex",
    category: "Duplex",
    price: "₦1,200,000",
    img: "/flat1.jpg",
  },
  {
    id: 12,
    title: "Modern Bungalow",
    category: "Bungalow",
    price: "₦2,200,000",
    img: "/flat3.jpg",
  },
  {
    id: 13,
    title: "Two Bedroom Apartment",
    category: "Apartment",
    price: "₦1,200,000",
    img: "/flat4.jpg",
  },
  {
    id: 14,
    title: "Modern Bungalow",
    category: "Bungalow",
    price: "₦1,200,000",
    img: "/flat9.jpg",
  },
  {
    id: 15,
    title: "Duplex",
    category: "Duplex",
    price: "₦1,200,000",
    img: "/flat8.jpg",
  },
  {
    id: 16,
    title: "Modern Bungalow",
    category: "Bungalow",
    price: "₦1,500,000",
    img: "/flat5.jpg",
  },
];

export default properties;
