export const PROPERTY_LIST = [
  {
    id: 1,
    price: "₦1,000,000",
    title: "Modern Bungalow",
    description:
      "Cozy rooms, large jacuzzi, spacious kitchen. Convenient lifestyle living.",
    image: "/Duplex.webp",
    added: "2 days ago",
    bathrooms: 2,
    bedrooms: 5,
    bathIcon: "/shawer.png",
    bedIcon: "/bed.png",
  },
  {
    id: 2,
    price: "₦1,000,000",
    title: "Luxury Apartment",
    description:
      "Modern finishings with 24/7 power supply in the heart of Lagos.",
    image: "/flat4.webp",
    added: "5 hours ago",

    bathrooms: 3,
    bedrooms: 4,
    bathIcon: "/shawer.png",
    bedIcon: "/bed.png",
  },
  {
    id: 3,
    price: "₦1,000,000",
    title: "Executive Duplex",
    description:
      "Spacious backyard, swimming pool, and premium security features.",
    image: "/flat1.webp",
    added: "1 day ago",
    bathrooms: 2,
    bedrooms: 5,
    bathIcon: "/shawer.png",
    bedIcon: "/bed.png",
  },
  {
    id: 4,
    price: "₦1,000,000",
    title: "Executive Duplex",
    description:
      "Spacious backyard, swimming pool, and premium security features.",
    image: "/flat3.webp",
    added: "1 day ago",
    bathrooms: 2,
    bedrooms: 5,
    bathIcon: "/shawer.png",
    bedIcon: "/bed.png",
  },
  {
    id: 5,
    price: "₦1,000,000",
    title: "Executive Duplex",
    description:
      "Spacious backyard, swimming pool, and premium security features.",
    image: "/flat6.webp",
    added: "1 day ago",
    bathrooms: 2,
    bedrooms: 5,
    bathIcon: "/shawer.png",
    bedIcon: "/bed.png",
  },
  {
    id: 6,
    price: "₦1,000,000",
    title: "Executive Duplex",
    description:
      "Spacious backyard, swimming pool, and premium security features.",
    image: "/Duplex.webp",
    added: "1 day ago",
    bathrooms: 2,
    bedrooms: 5,
    bathIcon: "/shawer.png",
    bedIcon: "/bed.png",
  },
];
