import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Provider";
import ToastProvider from "./components/ToastProvider";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "./components/context/AuthContext";
import GoogleOAuthClientProvider from "./components/auth/GoogleOAuthClientProvider";

export const metadata: Metadata = {
  title: "IDU GROUP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <GoogleOAuthClientProvider>
            <AuthProvider>
              <main>{children}</main>
            </AuthProvider>
          </GoogleOAuthClientProvider>
          <ToastProvider />
        </Providers>
      </body>
    </html>
  );
}
