import {
  DashboardMetrics,
  DashboardpropListings,
  RecentInquiries,
} from "../types";

export const DashboardListings: DashboardpropListings[] = [
  {
    id: 1,
    name: "Compact mini house",
    location: "Yaba, lagos",
    status: "Active",
    price: 950,
    inquiries: 24,
    views: 12,
    image: "/assets/dashboard-prop-img-1.png",
  },
  {
    id: 2,
    name: "Palm view apartment",
    location: "Lekki phase 1, lagos",
    status: "Pending",
    price: 200,
    inquiries: 32,
    views: 24,
    image: "/assets/dashboard-prop-img-2.png",
  },
  {
    id: 3,
    name: "Compact mini house",
    location: "Yaba, lagos",
    status: "Active",
    price: 950,
    inquiries: 24,
    views: 12,
    image: "/assets/dashboard-prop-img-3.png",
  },
  {
    id: 4,
    name: "Palm view apartment",
    location: "Lekki phase 1, lagos",
    status: "Rented",
    price: 950,
    inquiries: 24,
    views: 12,
    image: "/assets/dashboard-prop-img-4.png",
  },
  {
    id: 5,
    name: "Compact mini house",
    location: "Yaba, lagos",
    status: "Pending",
    price: 950,
    inquiries: 24,
    views: 12,
    image: "/assets/dashboard-prop-img-5.png",
  },
  {
    id: 6,
    name: "Palm view apartment",
    location: "Lekki phase 1, lagos",
    status: "Active",
    price: 950,
    inquiries: 24,
    views: 12,
    image: "/assets/dashboard-prop-img-6.png",
  },
  {
    id: 7,
    name: "Compact mini house",
    location: "Yaba, lagos",
    status: "Active",
    price: 950,
    inquiries: 24,
    views: 12,
    image: "/assets/dashboard-prop-img-7.png",
  },
];

export const Inquiries: RecentInquiries[] = [
  {
    id: 1,
    name: "Daniel Gbesimowo",
    message: "I’d like to know how everything wou...",
    figure: 4,
    image: "/assets/user-img-dash.png",
    isNew: true,
    lastMessageAt: "2026-07-20T10:15:00Z",
  },
  {
    id: 2,
    name: "IYKE IDU",
    message: "I’d like to know how everything wou...",
    figure: 3,
    image: "/assets/user-img-dash.png",
    lastMessageAt: "2026-07-20T09:40:00Z",
  },
  {
    id: 3,
    name: "Tommy Cjay",
    message: "I’d like to know how everything wou...",
    figure: 6,
    image: "/assets/user-img-dash.png",
    lastMessageAt: "2026-07-20T08:50:00Z",
  },
  {
    id: 4,
    name: "Adekunle James",
    message: "I’d like to know how everything wou...",
    figure: 2,
    image: "/assets/user-img-dash.png",
    lastMessageAt: "2026-07-20T08:15:00Z",
  },
  {
    id: 5,
    name: "Moyin Tamilore",
    message: "I’d like to know how everything wou...",
    figure: 2,
    image: "/assets/user-img-dash.png",
    lastMessageAt: "2026-07-20T07:30:00Z",
  },
  {
    id: 6,
    name: "Oluwaseun Mirabelle",
    message: "I’d like to know how everything wou...",
    figure: 4,
    image: "/assets/user-img-dash.png",
    lastMessageAt: "2026-07-20T06:45:00Z",
  },
];
